// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arithmetics.proto

#include "arithmetics.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace arithmetics {
class TwoValueRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TwoValueRequest> _instance;
} _TwoValueRequest_default_instance_;
class OneValueReplyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<OneValueReply> _instance;
} _OneValueReply_default_instance_;
}  // namespace arithmetics
static void InitDefaultsscc_info_OneValueReply_arithmetics_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::arithmetics::_OneValueReply_default_instance_;
    new (ptr) ::arithmetics::OneValueReply();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_OneValueReply_arithmetics_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_OneValueReply_arithmetics_2eproto}, {}};

static void InitDefaultsscc_info_TwoValueRequest_arithmetics_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::arithmetics::_TwoValueRequest_default_instance_;
    new (ptr) ::arithmetics::TwoValueRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TwoValueRequest_arithmetics_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_TwoValueRequest_arithmetics_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_arithmetics_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_arithmetics_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_arithmetics_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_arithmetics_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::arithmetics::TwoValueRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::arithmetics::TwoValueRequest, a_),
  PROTOBUF_FIELD_OFFSET(::arithmetics::TwoValueRequest, b_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::arithmetics::OneValueReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::arithmetics::OneValueReply, c_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::arithmetics::TwoValueRequest)},
  { 7, -1, sizeof(::arithmetics::OneValueReply)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::arithmetics::_TwoValueRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::arithmetics::_OneValueReply_default_instance_),
};

const char descriptor_table_protodef_arithmetics_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021arithmetics.proto\022\013arithmetics\"\'\n\017TwoV"
  "alueRequest\022\t\n\001a\030\001 \001(\005\022\t\n\001b\030\002 \001(\005\"\032\n\rOne"
  "ValueReply\022\t\n\001c\030\001 \001(\0052\243\002\n\013Arithmetics\022A\n"
  "\003Add\022\034.arithmetics.TwoValueRequest\032\032.ari"
  "thmetics.OneValueReply\"\000\022C\n\005Minus\022\034.arit"
  "hmetics.TwoValueRequest\032\032.arithmetics.On"
  "eValueReply\"\000\022F\n\010Multiply\022\034.arithmetics."
  "TwoValueRequest\032\032.arithmetics.OneValueRe"
  "ply\"\000\022D\n\006Divide\022\034.arithmetics.TwoValueRe"
  "quest\032\032.arithmetics.OneValueReply\"\000b\006pro"
  "to3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_arithmetics_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_arithmetics_2eproto_sccs[2] = {
  &scc_info_OneValueReply_arithmetics_2eproto.base,
  &scc_info_TwoValueRequest_arithmetics_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_arithmetics_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_arithmetics_2eproto = {
  false, false, descriptor_table_protodef_arithmetics_2eproto, "arithmetics.proto", 403,
  &descriptor_table_arithmetics_2eproto_once, descriptor_table_arithmetics_2eproto_sccs, descriptor_table_arithmetics_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_arithmetics_2eproto::offsets,
  file_level_metadata_arithmetics_2eproto, 2, file_level_enum_descriptors_arithmetics_2eproto, file_level_service_descriptors_arithmetics_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_arithmetics_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_arithmetics_2eproto)), true);
namespace arithmetics {

// ===================================================================

class TwoValueRequest::_Internal {
 public:
};

TwoValueRequest::TwoValueRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:arithmetics.TwoValueRequest)
}
TwoValueRequest::TwoValueRequest(const TwoValueRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&a_, &from.a_,
    static_cast<size_t>(reinterpret_cast<char*>(&b_) -
    reinterpret_cast<char*>(&a_)) + sizeof(b_));
  // @@protoc_insertion_point(copy_constructor:arithmetics.TwoValueRequest)
}

void TwoValueRequest::SharedCtor() {
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&a_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&b_) -
      reinterpret_cast<char*>(&a_)) + sizeof(b_));
}

TwoValueRequest::~TwoValueRequest() {
  // @@protoc_insertion_point(destructor:arithmetics.TwoValueRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void TwoValueRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void TwoValueRequest::ArenaDtor(void* object) {
  TwoValueRequest* _this = reinterpret_cast< TwoValueRequest* >(object);
  (void)_this;
}
void TwoValueRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TwoValueRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TwoValueRequest& TwoValueRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TwoValueRequest_arithmetics_2eproto.base);
  return *internal_default_instance();
}


void TwoValueRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:arithmetics.TwoValueRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&a_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&b_) -
      reinterpret_cast<char*>(&a_)) + sizeof(b_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TwoValueRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 a = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          a_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 b = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          b_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TwoValueRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:arithmetics.TwoValueRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 a = 1;
  if (this->a() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_a(), target);
  }

  // int32 b = 2;
  if (this->b() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_b(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:arithmetics.TwoValueRequest)
  return target;
}

size_t TwoValueRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:arithmetics.TwoValueRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 a = 1;
  if (this->a() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_a());
  }

  // int32 b = 2;
  if (this->b() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_b());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TwoValueRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:arithmetics.TwoValueRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const TwoValueRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TwoValueRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:arithmetics.TwoValueRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:arithmetics.TwoValueRequest)
    MergeFrom(*source);
  }
}

void TwoValueRequest::MergeFrom(const TwoValueRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:arithmetics.TwoValueRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.a() != 0) {
    _internal_set_a(from._internal_a());
  }
  if (from.b() != 0) {
    _internal_set_b(from._internal_b());
  }
}

void TwoValueRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:arithmetics.TwoValueRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TwoValueRequest::CopyFrom(const TwoValueRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:arithmetics.TwoValueRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TwoValueRequest::IsInitialized() const {
  return true;
}

void TwoValueRequest::InternalSwap(TwoValueRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TwoValueRequest, b_)
      + sizeof(TwoValueRequest::b_)
      - PROTOBUF_FIELD_OFFSET(TwoValueRequest, a_)>(
          reinterpret_cast<char*>(&a_),
          reinterpret_cast<char*>(&other->a_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TwoValueRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class OneValueReply::_Internal {
 public:
};

OneValueReply::OneValueReply(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:arithmetics.OneValueReply)
}
OneValueReply::OneValueReply(const OneValueReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  c_ = from.c_;
  // @@protoc_insertion_point(copy_constructor:arithmetics.OneValueReply)
}

void OneValueReply::SharedCtor() {
  c_ = 0;
}

OneValueReply::~OneValueReply() {
  // @@protoc_insertion_point(destructor:arithmetics.OneValueReply)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void OneValueReply::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void OneValueReply::ArenaDtor(void* object) {
  OneValueReply* _this = reinterpret_cast< OneValueReply* >(object);
  (void)_this;
}
void OneValueReply::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void OneValueReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const OneValueReply& OneValueReply::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_OneValueReply_arithmetics_2eproto.base);
  return *internal_default_instance();
}


void OneValueReply::Clear() {
// @@protoc_insertion_point(message_clear_start:arithmetics.OneValueReply)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  c_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OneValueReply::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 c = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          c_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* OneValueReply::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:arithmetics.OneValueReply)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 c = 1;
  if (this->c() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_c(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:arithmetics.OneValueReply)
  return target;
}

size_t OneValueReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:arithmetics.OneValueReply)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 c = 1;
  if (this->c() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_c());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void OneValueReply::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:arithmetics.OneValueReply)
  GOOGLE_DCHECK_NE(&from, this);
  const OneValueReply* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<OneValueReply>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:arithmetics.OneValueReply)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:arithmetics.OneValueReply)
    MergeFrom(*source);
  }
}

void OneValueReply::MergeFrom(const OneValueReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:arithmetics.OneValueReply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.c() != 0) {
    _internal_set_c(from._internal_c());
  }
}

void OneValueReply::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:arithmetics.OneValueReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OneValueReply::CopyFrom(const OneValueReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:arithmetics.OneValueReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OneValueReply::IsInitialized() const {
  return true;
}

void OneValueReply::InternalSwap(OneValueReply* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(c_, other->c_);
}

::PROTOBUF_NAMESPACE_ID::Metadata OneValueReply::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace arithmetics
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::arithmetics::TwoValueRequest* Arena::CreateMaybeMessage< ::arithmetics::TwoValueRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::arithmetics::TwoValueRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::arithmetics::OneValueReply* Arena::CreateMaybeMessage< ::arithmetics::OneValueReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::arithmetics::OneValueReply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
